FROM atomgraph/processor:eca779ec4a834289382a2173c63646cc30a0dc9a

COPY config/noi.ttl /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/it/bz/opendatahub/kg/noi.ttl
COPY config/location-mapping.n3 /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/custom-mapping.n3
COPY config/context.xml /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml