PREFIX  schema: <http://schema.org/>

SELECT  ?containsPlace
WHERE
  { ?this     schema:containsPlace  ?containsPlace .
    ?containsPlace
              schema:name           ?name
    FILTER langMatches(lang(?name), "en")
  }
ORDER BY ?name